name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint || echo 'Lint warnings'

      - name: Build
        run: npm run build

      - name: Package VSIX
        run: |
          npx @vscode/vsce --version
          npx @vscode/vsce package --out projectatlas-${{ github.sha }}.vsix
          ls -l *.vsix

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: projectatlas-vsix
          path: projectatlas-*.vsix
          if-no-files-found: error
